apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresDB
  labels:
    db: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      db: postgres
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: Aa123456


# add secret generator for password

