apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    db: postgres-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: sa
            - name: POSTGRES_PASSWORD
              value: Aa123456


# add secret generator for password

