apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    db: postgres
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: 5432
      targetPort: 3100